name: "AV Access"
version: "0.2.0"
slug: "av_access"
description: "Install and update the AV Access integration for Home Assistant."
url: "https://github.com/KeldorDE/Home-Assistant-AV-Access-App"
arch:
  - amd64
  - aarch64

startup: application
init: false

hassio_api: true
hassio_role: homeassistant

map:
  - type: homeassistant_config
    read_only: false
